-- Jalankan semua SQL ini di Supabase -> SQL Editor.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('crossword', 'wordsearch')),
  name text not null check (char_length(name) between 1 and 18),
  seconds integer not null check (seconds >= 0),
  score integer not null check (score >= 0),
  ts bigint not null
);

-- Aktifkan Row Level Security.
alter table public.leaderboard enable row level security;

-- Semua pengunjung boleh melihat leaderboard.
drop policy if exists "leaderboard_select_public" on public.leaderboard;
create policy "leaderboard_select_public"
on public.leaderboard
for select
to anon, authenticated
using (true);

-- Semua pengunjung boleh mengirim skor.
-- Untuk proyek kelas sederhana ini cukup; validasi anti-cheat penuh
-- sebaiknya dilakukan lewat server-side/Vercel Function.
drop policy if exists "leaderboard_insert_public" on public.leaderboard;
create policy "leaderboard_insert_public"
on public.leaderboard
for insert
to anon, authenticated
with check (
  game in ('crossword', 'wordsearch')
  and char_length(name) between 1 and 18
  and seconds >= 0
  and score >= 0
);

create index if not exists leaderboard_game_time_score_idx
on public.leaderboard (game, seconds asc, score desc);
